# Generated by Django 4.2.16 on 2024-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(blank=True, max_length=100, null=True)),
                ('CompanyAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
