# Generated by Django 4.2.16 on 2024-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleApp', '0002_manufacturetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductType', models.CharField(blank=True, max_length=100, null=True)),
                ('Manufacturedate', models.CharField(blank=True, max_length=100, null=True)),
                ('Expirydate', models.CharField(blank=True, max_length=100, null=True)),
                ('Uplaodphoto', models.FileField(blank=True, max_length=250, null=True, upload_to='')),
                ('Productprice', models.IntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
